package constants

const (
	EmailShorthandFlag        = "e"
	NameShorthandFlag         = "n"
	OrganizationShorthandFlag = "r"
	NamespaceShorthandFlag    = "i"
	SurnameShorthandFlag      = "s"
	UsernameShorthandFlag     = "u"
	QueryFlagShorthandFlag    = "q"
	IdsShorthandFlag          = "i"
	KindsShorthandFlag        = "k"
	SchemaNameShorthandFlag   = "n"
	VersionShorthandFlag      = "v"
	FilePathShorthandFlag     = "p"
	OutputShorthandFlag       = "o"
	KeyShorthandFlag          = "k"
	NamesShorthandFlag        = "n"
	VersionsShorthandFlag     = "v"
	SortShorthandFlag         = "s"
	AllServicesShorthandFlag  = "a"
	NodeIdShorthandFlag       = "n"
	ClusterIdShorthandFlag    = "c"
	ValueShorthandFlag        = "v"
	MaintainerShorthandFlag   = "m"
	LabelsShorthandFlag       = "l"
	LayersShorthandFlag       = "ly"
)
