package constants

const (
	EmailDescription              = "Email for registration"
	NameDescription               = "Name for registration"
	SurnameDescription            = "Surname for registration"
	UsernameDescription           = "Username for registration"
	NodeQueryDescription          = "Query label for finding specific nodes"
	NodeQueryRequiredDescription  = "Query label for finding specific nodes (required)"
	IdsDescription                = "IDs of the entities separated by '|' (required)"
	KindsDescription              = "Kinds of the entities separated by '|' (required)"
	OrganizationDescription       = "Organization name (required)"
	NamespaceDescription          = "Namespace name (required)"
	SchemaNameDescription         = "Schema name (required)"
	VersionDescription            = "Version of entity (required)"
	FilePathDescription           = "Path to the YAML or JSON file (required)"
	OutputDescription             = "Output format (json or yaml)"
	NodeIdDescription             = "Node ID (required)"
	ClusterIdDescription          = "Cluster ID"
	LabelKeyDescription           = "Label key (required)"
	ConfigDiffNamesDescription    = "Configuration names separated by '|' (required)"
	ConfigDiffVersionsDescription = "Configuration versions separated by '|' (required)"
	AllServicesDescription        = "Display metrics for all app services (optional)"
	SortMetricsDescription        = "Sort metrics by 'cpu' (default), 'memory', 'disk', 'network receive', 'network transmit' or 'bandwidth'"
	LabelValueDescription         = "Label value (required)"
)
