package constants

const (
	EmailFlag         = "email"
	NameFlag          = "name"
	SurnameFlag       = "surname"
	UsernameFlag      = "username"
	OrganizationFlag  = "org"
	NamespaceFlag     = "namespace"
	QueryFlag         = "query"
	IdsFlag           = "ids"
	IdFlag            = "id"
	KindsFlag         = "kinds"
	SchemaNameFlag    = "schema-name"
	VersionFlag       = "version"
	FilePathFlag      = "path"
	OutputFlag        = "output"
	NodeIdFlag        = "node-id"
	ClusterIdFlag     = "cluster-id"
	KeyFlag           = "key"
	NamesFlag         = "names"
	VersionsFlag      = "versions"
	AllServicesFlag   = "all-services"
	SortByFlag        = "sort-by"
	ValueFlag         = "value"
	MaintainerFlag    = "maintainer"
	SchemaVersionFlag = "schema-version"
	LabelsFlag        = "labels"
	LayersFlag        = "layers"
	KindFlag          = "kind"
	OldVersionFlag    = "old-version"
	NewVersionFlag    = "new-version"
	DescriptionFlag   = "description"
	TagFlag           = "tag"
)
