package constants

const (
	ShortLoginDesc                           = "Login into application"
	ShortRegisterDesc                        = "Register a new user"
	ClaimNodesShortDesc                      = "Claim nodes for an organization based on specific criteria"
	CreatePoliciesShortDesc                  = "Create policies from YAML or JSON file"
	CreateAppShortDesc                       = "Create app from YAML or JSON file"
	CreateNamespaceShortDesc                 = "Create namespace from YAML or JSON file"
	CreateRelationsShortDesc                 = "Create relations between entities"
	CreateSchemaShortDesc                    = "Create a schema for an organization"
	CreateStarmapShortDesc                   = "Create a starmap"
	ExtendStarmapShortDesc                   = "Extend existing chart"
	UpdateStarmapShortDesc                   = "Update starmap chart"
	DeleteConfigGroupShortDesc               = "Delete a configuration group version"
	DeleteNodeLabelsShortDesc                = "Delete a label from a node"
	DeleteSchemaShortDesc                    = "Delete a schema"
	DeleteAppShortDesc                       = "Delete an app"
	DeleteNamespaceShortDesc                 = "Delete a namespace"
	DeleteStandaloneConfigShortDesc          = "Delete a standalone configuration version"
	DeleteStarmapChartShortDesc              = "Delete Starmap chart"
	DiffConfigGroupShortDesc                 = "Compare two configuration groups"
	DiffStandaloneConfigShortDesc            = "Compare two configuration groups"
	StarmapSwitchCheckpointShortDesc         = "Compares two versions of the same chart"
	GetAppConfigShortDesc                    = "Retrieve and display the configuration"
	GetStandaloneConfigShortDesc             = "Retrieve and display the standalone configuration"
	GetStarmapChartByMetadataShortDesc       = "Retrieve Starmap chart by metadata"
	GetStarmapChartByIdShortDesc             = "Retrieve Starmap chart by id"
	GetStarmapAllChartsShortDesc             = "Retrieve all Starmap charts"
	GetStarmapChartsByLabelsShortDesc        = "Retrieve Starmap charts by labels"
	GetStarmapChartMissingLayersShortDesc    = "Retrieve Starmap chart missing layers"
	GetStarmapChartTimelineShortDesc         = "Retrieve chronological view of all versions of a chart"
	SearchStarmapShortDesc                   = "Search Starmap components"
	LatestMetricsShortDesc                   = "Retrieve and display the latest metrics"
	GetSchemaShortDesc                       = "Retrieve and display the schema"
	GetSchemaVersionShortDesc                = "Retrieve and display schema versions"
	AllocatedNodesShortDesc                  = "Retrieve and display organization nodes"
	ListConfigGroupPlacementsShortDesc       = "Retrieve and display the configuration group placements"
	ListNodesShortDesc                       = "Retrieve and display all available nodes"
	ListStandaloneConfigShortDesc            = "Retrieve and display all standalone configurations"
	ListStandaloneConfigPlacementsShortDesc  = "Retrieve and display all the standalone configuration placements"
	PlaceConfigGroupPlacementsShortDesc      = "Place configuration group placements"
	PlaceStandaloneConfigPlacementsShortDesc = "Place standalone configuration placements"
	PutConfigGroupShortDesc                  = "Saves configuration group"
	ShortLabelDesc                           = "Add a label to a node."
	PutStandaloneConfigShortDesc             = "Saves standalone configuration"
	ValidateSchemaVersionShortDesc           = "Validate a schema version"
)
