config:
  name: db_config
  organization: c12s
  namespace: default
  version: v1.0.0
strategy:
  name: gossip
  percentage: 50
  # query:
  #   - labelKey: newlabel
  #     shouldBe: ">"
  #     value: "2"
